### ISSUE TITLE
Fixa så att tjänsterna kan köra på våran molnserver

### ISSUE THREAD

**Issue by joelbinn** [CAG-Contactor/racing-management-system#53]

**Comment by breiler** [comment]
För att lättare kunna konfigurera reverse proxy för komponenterna hade det varit bra om alla applikationer har en egen context-path. Det är enkelt att lägga till i application.properties:
server.context-path=/client-api

Detta kräver att de applikationer som integrerar mot andra måste ändra sin defaultkonfiguration för endpoints, exempelvis:
server.leaderboard.base.uri=http://localhost:10180/leaderboard
server.currentrace.base.uri=http://localhost:10080/current-race
server.clientapi.base.uri=http://localhost:10580/client-api
